baseURL = "https://rizcaca.github.io/"
languageCode = 'en-us'
title = 'Rizcaca'
theme = 'pehtheme-hugo'

paginate = '6' # <- Set the desired number of posts per page 
summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com
relativeURLs = true
canonifyURLs = true

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = "Let's grow and glow!!"
	mainSections = 'posts'

[author]
	name = 'Rizka Afriani Tandipayuk'
	bio = "Let's grow and glow!!"
	avatar = '/images/avatarrizcaca.jpeg'
	twitter = 'https://x.com/rizcacaaaa'

[menu] # Menu management
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 2
	[[menu.main]]
		name = 'About'
		pageRef = '/about'
		weight = 5
	[[menu.main]]
		name = 'Posts'
		pageRef = '/posts'
		weight = 5

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'