# [build]
#   publish = "public"
#   command = "hugo --gc --minify --themesDir themes"
[build]
  publish = "static/admin" # Publishing only the admin interface
  command = "echo 'Skipping site build on Netlify'" # Skipping the build process

[context.production.environment]
  HUGO_VERSION = "0.123.7"
  HUGO_BASEURL = "https://rizcasaur.us/"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200